// --------------------------------------------------------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs" company="StealFocus">
//   Copyright StealFocus. All rights reserved.
// </copyright>
// <summary>
//   AssemblyInfo.cs
// </summary>
// --------------------------------------------------------------------------------------------------------------------

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009AddAdapter.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009CleanHostQueue.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009CreateApplication.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogError(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009CreateHost.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009CreateHost.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009CreateHostInstance.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009CreateReceiveHandler.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009CreateSendHandler.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009DeleteAllReceiveHandlers.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009DeleteAllSendHandlers.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009DeleteHost.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009DeleteReceiveHandler.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009DeleteSendHandler.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009DisableAllReceiveLocations.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009DisableReceiveLocations.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009EnableAllReceiveLocations.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009EnableReceiveLocations.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009RemoveApplication.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009StartAllOrchestrations.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009StartAllSendPorts.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009StartApplication.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009StartHost.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009StartOrchestrations.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009StartSendPorts.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009StopAllSendPorts.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009StopApplication.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009StopHost.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009StopSendPorts.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009TerminateAllOrchestrations.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.Build.Utilities.TaskLoggingHelper.LogMessage(System.String,System.Object[])", Scope = "member", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009TerminateOrchestrations.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "StealFocus.MSBuild.Tasks.BizTalk2009.Bts2009CleanHostQueue")]
